apiVersion: v1
kind: Secret
metadata:
  name: aerive-secrets
  namespace: aerive
type: Opaque
stringData:
  SUPABASE_DB_URL: "postgresql://postgres:devdatta_db_pass@db.eihqtmiwyqspaxqrovul.supabase.co:5432/postgres"
  REDIS_PASSWORD: ""
  JWT_SECRET: "vfszj3xu/LRQeRKcpKsrBUsRsGx+sVCASf2uX7M596E="
  ENCRYPTION_KEY: "bf7aec3bfb2c628e5611a51ceed4e64a13ce65dd894866248343cdafaeaa3eef"
  MONGODB_URI: "mongodb+srv://dygandole_db_user:dygandole_db_pass@aerive.ajaohyp.mongodb.net/aerive?appName=Aerive&retryWrites=true&w=majority"

